version: '27.2.0'

services:
  mysql_container:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: Booky  
     ## MYSQL_USER: root
      #MYSQL_PASSWORD: myuser  
      MYSQL_ROOT_PASSWORD: root


    ports:
      - "3306:3306"  
    volumes:
      - mysql_container-data:/var/lib/mysql  

  backend:
    build:
      context: ./booky-bakend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/Booky?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  
    ports:
      - "8080:8080"  
    depends_on:
      -  mysql_container

  frontend:
    build:
      context: ./booky-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    depends_on:
      - backend

volumes:
  mysql_container-data:  
