version: '1.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: booky
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./booky-bakend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/booky
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./booky-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
